### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by TheShadowGamer**
Thanks to AAGaming for helping with this.

### CODE REVIEW

**Comment by TheShadowGamer** [comment]
None. Just there if you wanna console.log it at any time ig.

**Comment by LandenStephenss** [comment]
Then theres no point in having it in this code. Remove it and i will test

**Comment by TheShadowGamer** [comment]
It has a small use. 
```
pluginWillUnload() {
      if (!suppress) {
        document.body.removeEventListener("keyup", this.keyup);
      }
  }
```
Ill test without it soon

**Comment by TheShadowGamer** [comment]
Removing that if statement breaks it so

**Comment by LandenStephenss** [comment]
You dont need the if() {}, since the value never changes.  You can just have the remove eventListener.
As far as i can tell this PR is worthless

**Comment by TheShadowGamer** [comment]
It’s not really useless? Try using your version, it doesn’t work (at least not for me).

**Comment by LandenStephenss** [comment]
Panikk has always worked for me. I dont use powercord anymore though so i cant really test it

**Comment by TheShadowGamer** [comment]
The one you have doesn't work for me or a few others.

**Comment by TheShadowGamer** [comment]
If you dont want to merge it thats fine.

**Pull request merged**
